### ISSUE TITLE
Altitude doesn't change in MS5611_example sketch

### ISSUE THREAD

**Issue by JeffB42** [Patrikpcm/MS5611-Library#1]
I'm exploring your MS5611 library, with the intention of using it for an altimeter.  I have a GY-63 board, which uses the MS5611, and have it connected to an Arduino Uno.  I was able to run the MS5611_altitude_example sketch without any issues (other than the altitude drift, but that's a different issue).  However, when I run the other sketch, MS5611_example, it runs, and the temperature and pressure change, but the computed altitude always stays at 934 m.

Looking through the code, there's:
```#define ALTITUDE 934.0```
...and although my elevation probably isn't 934m, I left it at 934 for now.

Then in the loop, we have:
```
status = pressure.getTemperature(T, 1);
status = pressure.getPressure(P,T,1);
// Result: p0 = sea-level compensated pressure in mb
p0 = pressure.sealevel(P,ALTITUDE);
```

...and then at the end there is:
```a = pressure.altitude(P,p0);```

When I run the sketch, the measured temperature and the calculated/sea-level compensated pressure change, but the altitude (a) always remains at 934.0 meters, even when I raise the sensor 5 or so feet above its resting position.

Here is some sample output:
```

provided altitude: 934 meters
Temperature: 23.99 deg C
absolute pressure: 1007.10 mb
relative (sea-level) pressure: 1126.34 mb
computed altitude: 934.00 meters

provided altitude: 934 meters
Temperature: 24.02 deg C
absolute pressure: 1007.25 mb
relative (sea-level) pressure: 1126.51 mb
computed altitude: 934.00 meters

provided altitude: 934 meters
Temperature: 24.05 deg C
absolute pressure: 1007.28 mb
relative (sea-level) pressure: 1126.55 mb
computed altitude: 934.00 meters

provided altitude: 934 meters
Temperature: 24.05 deg C
absolute pressure: 1007.27 mb
relative (sea-level) pressure: 1126.53 mb
computed altitude: 934.00 meters

provided altitude: 934 meters
Temperature: 24.06 deg C
absolute pressure: 1007.26 mb
relative (sea-level) pressure: 1126.52 mb
computed altitude: 934.00 meters
```
(during the reading, I raised the sensor 5 or so feet, and then lowered it back dow to the initial elevation)

I'm new to the library, and I can't tell if this is expected or not.

**Comment by Patrikpcm** [comment]
Hello JeffB42,
Thanks for reporting this issue.
I reviewed the entire code, apparently it is working fine.
However, in this specific example he is always reporting the same altitude.
Checking the calculations I noticed that the Arduino is rounding the calculations ​​a lot without an apparent reason (maybe because of the predefined altitude).

But the good news is that the code works. In other example models I wrote, the altitude changed as expected.
